src/Entity/Acheter.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AcheterRepository")
 */
class Acheter
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="date")
     */
    private $dateAchat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Eleve", inversedBy="acheters")
     * @ORM\JoinColumn(nullable=false)
     */
    private $eleve;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Accessoire", inversedBy="acheters")
     * @ORM\JoinColumn(nullable=false)
     */
    private $accessoire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Annee", inversedBy="acheters")
     * @ORM\JoinColumn(nullable=false)
     */
    private $annee;
    /** 
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    public function __construct(){
        $this->dateAchat = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->dateAchat;
    }

    public function setDateAchat(\DateTimeInterface $dateAchat): self
    {
        $this->dateAchat = $dateAchat;

        return $this;
    }

    public function getEleve(): ?Eleve
    {
        return $this->eleve;
    }

    public function setEleve(?Eleve $eleve): self
    {
        $this->eleve = $eleve;

        return $this;
    }

    public function getAccessoire(): ?Accessoire
    {
        return $this->accessoire;
    }

    public function setAccessoire(?Accessoire $accessoire): self
    {
        $this->accessoire = $accessoire;

        return $this;
    }

    public function getAnnee(): ?Annee
    {
        return $this->annee;
    }

    public function setAnnee(?Annee $annee): self
    {
        $this->annee = $annee;

        return $this;
    }
    
    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }


}

src/Entity/Annee.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnneeRepository")
 */
class Annee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $dateFin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Inscription", mappedBy="annee", orphanRemoval=true)
     */
    private $inscriptions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Appartenir", mappedBy="annee", orphanRemoval=true)
     */
    private $appartenirs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Pansion", mappedBy="annee", orphanRemoval=true)
     */
    private $pansions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Acheter", mappedBy="annee", orphanRemoval=true)
     */
    private $acheters;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Depense", mappedBy="annee", orphanRemoval=true)
     */
    private $depenses;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
        $this->appartenirs = new ArrayCollection();
        $this->pansions = new ArrayCollection();
        $this->acheters = new ArrayCollection();
        $this->depenses = new ArrayCollection();
    }

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->getDateDebut();
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    /**
     * @return Collection|Inscription[]
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions[] = $inscription;
            $inscription->setAnnee($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): self
    {
        if ($this->inscriptions->contains($inscription)) {
            $this->inscriptions->removeElement($inscription);
            // set the owning side to null (unless already changed)
            if ($inscription->getAnnee() === $this) {
                $inscription->setAnnee(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Appartenir[]
     */
    public function getAppartenirs(): Collection
    {
        return $this->appartenirs;
    }

    public function addAppartenir(Appartenir $appartenir): self
    {
        if (!$this->appartenirs->contains($appartenir)) {
            $this->appartenirs[] = $appartenir;
            $appartenir->setAnnee($this);
        }

        return $this;
    }

    public function removeAppartenir(Appartenir $appartenir): self
    {
        if ($this->appartenirs->contains($appartenir)) {
            $this->appartenirs->removeElement($appartenir);
            // set the owning side to null (unless already changed)
            if ($appartenir->getAnnee() === $this) {
                $appartenir->setAnnee(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Pansion[]
     */
    public function getPansions(): Collection
    {
        return $this->pansions;
    }

    public function addPansion(Pansion $pansion): self
    {
        if (!$this->pansions->contains($pansion)) {
            $this->pansions[] = $pansion;
            $pansion->setAnnee($this);
        }

        return $this;
    }

    public function removePansion(Pansion $pansion): self
    {
        if ($this->pansions->contains($pansion)) {
            $this->pansions->removeElement($pansion);
            // set the owning side to null (unless already changed)
            if ($pansion->getAnnee() === $this) {
                $pansion->setAnnee(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Acheter[]
     */
    public function getAcheters(): Collection
    {
        return $this->acheters;
    }

    public function addAcheter(Acheter $acheter): self
    {
        if (!$this->acheters->contains($acheter)) {
            $this->acheters[] = $acheter;
            $acheter->setAnnee($this);
        }

        return $this;
    }

    public function removeAcheter(Acheter $acheter): self
    {
        if ($this->acheters->contains($acheter)) {
            $this->acheters->removeElement($acheter);
            // set the owning side to null (unless already changed)
            if ($acheter->getAnnee() === $this) {
                $acheter->setAnnee(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Depense[]
     */
    public function getDepenses(): Collection
    {
        return $this->depenses;
    }

    public function addDepense(Depense $depense): self
    {
        if (!$this->depenses->contains($depense)) {
            $this->depenses[] = $depense;
            $depense->setAnnee($this);
        }

        return $this;
    }

    public function removeDepense(Depense $depense): self
    {
        if ($this->depenses->contains($depense)) {
            $this->depenses->removeElement($depense);
            // set the owning side to null (unless already changed)
            if ($depense->getAnnee() === $this) {
                $depense->setAnnee(null);
            }
        }

        return $this;
    }

}

src/Entity/Pansion.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PansionRepository")
 */
class Pansion
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datePaiement;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Eleve", inversedBy="pansions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $eleve;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Salle", inversedBy="pansions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $salle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tranche", mappedBy="pansion", orphanRemoval=true)
     */
    private $tranches;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Annee", inversedBy="pansions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $annee;

    public function __construct()
    {
        $this->tranches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDatePaiement(): ?\DateTimeInterface
    {
        return $this->datePaiement;
    }

    public function setDatePaiement(\DateTimeInterface $datePaiement): self
    {
        $this->datePaiement = $datePaiement;

        return $this;
    }

    public function getEleve(): ?Eleve
    {
        return $this->eleve;
    }

    public function setEleve(?Eleve $eleve): self
    {
        $this->eleve = $eleve;

        return $this;
    }

    public function getSalle(): ?Salle
    {
        return $this->salle;
    }

    public function setSalle(?Salle $salle): self
    {
        $this->salle = $salle;

        return $this;
    }

    /**
     * @return Collection|Tranche[]
     */
    public function getTranches(): Collection
    {
        return $this->tranches;
    }

    public function addTranch(Tranche $tranch): self
    {
        if (!$this->tranches->contains($tranch)) {
            // $this->tranches[] = $tranch;
            $this->tranches->add($tranch);
            $tranch->setPansion($this);
        }

        return $this;
    }

    public function removeTranch(Tranche $tranch): self
    {
        if ($this->tranches->contains($tranch)) {
            $this->tranches->removeElement($tranch);
            // set the owning side to null (unless already changed)
            if ($tranch->getPansion() === $this) {
                $tranch->setPansion(null);
            }
        }

        return $this;
    }

    public function getReste()
    {
        $res = $this->getMontant();

        foreach ($this->getTranches() as $tranche) {
            $res -= $tranche->getMontant();
        }
        return $res;
    }

    public function getMontantVerser()
    {
        return $this->getMontant() - $this->getReste();
    }

    public function getAnnee(): ?Annee
    {
        return $this->annee;
    }

    public function setAnnee(?Annee $annee): self
    {
        $this->annee = $annee;

        return $this;
    }
}

src/Form/AcheterType.php
<?php

namespace App\Form;

use App\Entity\Acheter;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AcheterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('accessoire')
            ->add('prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Acheter::class,
        ]);
    }
}

src/Controller/AcheterController.php
<?php

namespace App\Controller;

use App\Entity\Acheter;
use App\Form\AcheterType;
use App\Repository\AcheterRepository;
use App\Repository\EleveRepository;
use App\Repository\AnneeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Options;
use Dompdf\Dompdf;

/**
 * @Route("/acheter")
 */
class AcheterController extends AbstractController
{
    /**
     * @Route("/", name="acheter_index", methods={"GET"})
     */
    public function index(AcheterRepository $acheterRepository): Response
    {
        return $this->render('acheter/index.html.twig', [
            'acheters' => $acheterRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{id}", name="acheter_new", methods={"GET","POST"})
     */
    public function new(Request $request,
                        $id,
                        EleveRepository $eleveRepository,
                        AnneeRepository $anneeRepository,
                        AcheterRepository $acheterRepository): Response
    {
        $annee = $anneeRepository->AnneeEnCours();
        $eleve = $eleveRepository->findOneById($id);
        $acheter = new Acheter();
        $form = $this->createForm(AcheterType::class, $acheter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $acheter->setEleve($eleve);
            $acheter->setAnnee($annee);
            $acheter->setCode($acheterRepository->genCode());
            // $entityManager->persist($acheter);
            // $entityManager->flush();

            $entityManager = $this->getDoctrine()->getManager();
            try{
                $entityManager->persist($acheter);
                $entityManager->flush();
                $this->addFlash('success', 'Achat effecuté avec succès');
            }catch(Exception $ex){
                $this->addFlash('error', 'Une erreur est survenue lors de l\'achat.');
                return null;
            }
            $this->addFlash('success', 'Achat effecuté avec succès.');

            $options = new Options();
            $options->set('isRemoteEnabled', TRUE);
            
            $dompdf = new Dompdf($options);

            $context = stream_context_create([ 
                'ssl' => [
                    'verify_peer' => FALSE, 
                    'verify_peer_name' => FALSE,
                    'allow_self_signed'=> TRUE
                ]
            ]);

            $dompdf->setHttpContext($context);
            // var_dump(end($tranches)); die;

            $annee = $anneeRepository->AnneeEnCours();
            $html = $this->renderView('acheter/print_recu.html.twig', [
                'eleve' => $eleve,
                'acheter' => $acheter,
                'annee' => $annee,
            ]);
            $dompdf->loadHtml($html);
            $dompdf->setPaper('A5', 'landscape');

            try{
                $dompdf->render();
                return new Response($dompdf->stream($acheter->getCode().".pdf", ["Attachment" => false]), 200, array('Content-Type' => 'application/pdf'));
            }catch(Exception $ex){
                $this->addFlash('error', 'Une erreur est survenue lors de la generation du recu.');
                return $this->redirectToRoute('acheter_new', ['id'=>$id]);
                // die($ex);
            }
        }

        return $this->render('acheter/new.html.twig', [
            'acheter' => $acheter,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="acheter_show", methods={"GET"})
     */
    public function show(Acheter $acheter): Response
    {
        return $this->render('acheter/show.html.twig', [
            'acheter' => $acheter,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="acheter_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Acheter $acheter): Response
    {
        $form = $this->createForm(AcheterType::class, $acheter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('acheter_index');
        }

        return $this->render('acheter/edit.html.twig', [
            'acheter' => $acheter,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="acheter_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Acheter $acheter): Response
    {
        if ($this->isCsrfTokenValid('delete'.$acheter->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($acheter);
            $entityManager->flush();
        }

        return $this->redirectToRoute('acheter_index');
    }
}

templates/acheter/_delete_form.html.twig
<form method="post" action="{{ path('acheter_delete', {'id': acheter.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ acheter.id) }}">
    <button class="btn">Delete</button>
</form>

templates/acheter/_form.html.twig
{{ form_start(form) }}
   <div class="panel-body">
    {{ form_widget(form) }}
   <div class=" text-center">
                    <button class="btn btn-info">{{ button_label|default('Enregistrer')}}</button>
             </div>
{{ form_end(form) }}

templates/acheter/edit.html.twig
{% extends 'template.html.twig' %}

{% block title %}Edit Acheter{% endblock %}

{% block body %}
    <h1>Edit Acheter</h1>

    {{ include('acheter/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('acheter_index') }}">back to list</a>

    {{ include('acheter/_delete_form.html.twig') }}
{% endblock %}

templates/acheter/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}Achat | liste{% endblock %}

{% block hearder %}
    <div class="pageheader">
        <h3><i class="fa fa-home"></i> Achat </h3>
        <div class="breadcrumb-wrapper">
            <span class="label">vous êtes ici:</span>
            <ol class="breadcrumb">
                <li class=""> <a href="{{ path('accueil') }}">Accueil</a></li>
                <li class=""> <a href="#">Achat</a></li>
                <li class="active"> <a class="text-bold" href="{{ path('acheter_index') }}">Liste</a></li>
            </ol>
        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title" style="text-align: center;">Acheter</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Produit</th>
                        <th>Prix</th>
                        <th>DateAchat</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for acheter in acheters %}
                    <tr>
                        <td>{{ acheter.id }}</td>
                        <td>{{ acheter.accessoire.libelle|upper }}</td>
                        <td>{{ acheter.prix }}</td>
                        <td>{{ acheter.dateAchat ? acheter.dateAchat|date('Y-m-d') : '0000-00-00' }}</td>
                        <td>
                            <a class="" href="{{ path('acheter_show', {'id': acheter.id}) }}">show</a>
                            <a class="" href="{{ path('acheter_edit', {'id': acheter.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td class="text-center" colspan="4">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/acheter/new.html.twig
{% extends 'template.html.twig' %}
{% block title %}
 Accessoires | Ajout   
{% endblock %}
{% block hearder %}
<div class="pageheader">
    <h3>
        <i class="fa fa-home"></i>Accueil
    </h3>
    <div class="breadcrumb-wrapper">
        <span class="label">vous êtes ici:</span>
        <ol class="breadcrumb">
            <li>
                <a href="#">
                    Accueil
                </a>
            </li>
            <li class="active">
                Achat accessoire
            </li>
        </ol>
    </div>
</div>
{% endblock %}

{% block body %}
    <div class="col-sm-6 eq-box-sm">
    {% for message in app.flashes('success') %}
        <div class="btn btn-success">
        {{message}}
        </div>
    {% endfor %}
    <br>
    <div class="panel-heading">
        <div class="panel-control">
            <a class="btn btn-info" href="{{ path('accessoire_index') }}" title="Retour à la liste"><i class="fa fa-chevron-left"></i></a>
            
        </div>
        <h3 class="panel-title">Effectuer un achat d'accessoire</h3>
    </div>

    {{ include('acheter/_form.html.twig') }}
{% endblock %}

templates/acheter/print_recu.html.twig
{% extends 'print/recu_base.html.twig' %}
{% block title %}RECU DE PAIEMENT DE(S) ACCESSOIRE(S) - {{acheter.code}}{% endblock %}
{% block name %}<div><u>RECU DE PAIEMENT DE(S) ACCESSOIRE(S)</u><br><i class="text-small">Accessory payment receipt</i></div>{% endblock %}

{% block body %}
  <br style="line-height: 0.4cm;">
  <table class="col-pk-12">
    <tr class="text-small">
      <td class="col-pk-4 text-left">N<sup>o</sup>: <span class="text-bold">{% if acheter.id > 9999 %} {{(acheter.id % 10000) | strpad(4,'0', 'left')}} {% else %} {{acheter.id | strpad(4,'0', 'left')}} {% endif %}/ {{annee.dateDebut | date("y")}}</span></td>
      <td class="col-pk-4 text-right">Annee Scolaire: <span class="text-bold">{{annee.dateDebut | date("Y")}} - {{annee.dateFin | date("Y")}}</span></td>
      <td class="col-pk-4 text-right">CODE: <span class="text-bold">{{acheter.code}}</span></td>
    </tr>
    <tr><td class="col-pk-12" colspan="3">Matricule: <span class="text-bold">{{eleve.matricule}}</span></td></tr>
    <tr><td class="col-pk-12" colspan="3">Nom et Prenom: <span class="text-bold">{{eleve.nom | upper}} {{eleve.prenom | capitalize}}</span></td></tr>
    <tr>
      <td class="col-pk-4">Date de Naissance: <span class="text-bold">{{eleve.dateDeNaissance | date("d/m/Y")}}</span></td>
      <td class="col-pk-4">Lieu de Naissance: <span class="text-bold">{{eleve.lieuDeNaissance}}</span></td>
      {# <td class="col-pk-4">Montant Total: <span class="text-bold">{{pansion.montant}} XAF</span></td> #}
    </tr>
    <tr>
      <td class="col-pk-4">Sexe: <span class="text-bold">{{eleve.sexe}}</span></td>
      <td class="col-pk-4">Nationalite: <span class="text-bold">{{eleve.nationalite}}</span></td>
      {# <td class="col-pk-4">Montant versé: <span class="text-bold">{{acheter.montant}} XAF</span></td> #}
    </tr>
    <tr>
      <td class="col-pk-4">Salle: <span class="text-bold">{{eleve.salle.libelle}}</span></td>
      <td class="col-pk-4">Classe: <span class="text-bold">{{eleve.salle.classe.libelle}}</span></td>
      {# <td class="col-pk-4">Reste à payer: <span class="text-bold">{{pansion.reste}} XAF</span></td> #}
    </tr>
    <tr><td class="col-pk-4" colspan="3"><br></td></tr>
    <tr class="bordered text-bold thead">
      <td class="col-pk-4">Produit</td>
      <td class="col-pk-4">Prix</td>
      <td class="col-pk-4">Total</td>
    </tr>
    <tr class="bordered">
      <td class="col-pk-4">{{acheter.accessoire.libelle|upper}}</td>
      <td class="col-pk-4 text-right">{{acheter.prix}}</td>
      <td class="col-pk-4 text-bold text-right thead">{{acheter.prix}} XAF</td>
    </tr>
    <tr class="bordered">
      <td class="col-pk-8 text-bold text-center" colspan="2">TOTAL</td>
      <td class="col-pk-4 text-bold text-right thead">{{acheter.prix}} XAF</td>
    </tr>
    <tr><td class="col-pk-4" colspan="3"><br></td></tr>
    <tr class="text-center">
      <td class="col-pk-4"><u>Visa Etablisement</u></td>
      <td class="col-pk-4"></td>
      <td class="col-pk-4"><u>Visa Parent</u></td>
    </tr>
    <tr><td class="col-pk-4" colspan="3" style="height: 0.84cm;"></td></tr>
    <tr>
      <td class="col-pk-4 text-right text-x-small" colspan="3">Date de paiement: <span class="text-bold">{{acheter.dateAchat | date("d/m/Y")}}</span></td>
    </tr>
  </table>
{% endblock %}

templates/acheter/show.html.twig
{% extends 'template.html.twig' %}

{% block title %}Acheter{% endblock %}

{% block body %}
    <h1>Acheter</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ acheter.id }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ acheter.prix }}</td>
            </tr>
            <tr>
                <th>DateAchat</th>
                <td>{{ acheter.dateAchat ? acheter.dateAchat|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('acheter_index') }}">back to list</a>

    <a href="{{ path('acheter_edit', {'id': acheter.id}) }}">edit</a>

    {{ include('acheter/_delete_form.html.twig') }}
{% endblock %}